## Naive Bayes Algorithm 

In [3]:
import pandas as pd 

import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.datasets import load_iris
from sklearn.naive_bayes import GaussianNB

In [2]:
# load the data set 
load_iris = load_iris()
X = load_iris.data
Y = load_iris.target

# split the data set into train and test

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=42)


In [5]:
# model initialization the guaisian naive bayes model

gnb = GaussianNB()

# Train the model 
gnb.fit(X_train, Y_train)

# predict the model 
Y_pred = gnb.predict(X_test)


# model evaluation

print("Accuracy Score: ", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix: ", confusion_matrix(Y_test, Y_pred))
print("Classification Report: ", classification_report(Y_test, Y_pred))


Accuracy Score:  0.9777777777777777
Confusion Matrix:  [[19  0  0]
 [ 0 12  1]
 [ 0  0 13]]
Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.92      0.96        13
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted avg       0.98      0.98      0.98        45



In [7]:
from sklearn.naive_bayes import MultinomialNB
#  multinomial model 
# initialize the model
mnb = MultinomialNB()

# train the model 
mnb.fit(X_train, Y_train)

# predict the model 
Y_pred = mnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix: ", confusion_matrix(Y_test, Y_pred))
print("Classification Report: ", classification_report(Y_test, Y_pred))


Accuracy Score:  0.9555555555555556
Confusion Matrix:  [[19  0  0]
 [ 0 12  1]
 [ 0  1 12]]
Classification Report:                precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [8]:
# bernoulli model
from sklearn.naive_bayes import BernoulliNB

# initialize the model
bnb = BernoulliNB()

# train the model
bnb.fit(X_train, Y_train)

# predict the model
Y_pred = bnb.predict(X_test)

# evaluate the model
print("Accuracy Score: ", accuracy_score(Y_test, Y_pred))
print("Confusion Matrix: ", confusion_matrix(Y_test, Y_pred))
print("Classification Report: ", classification_report(Y_test, Y_pred))

Accuracy Score:  0.28888888888888886
Confusion Matrix:  [[ 0 19  0]
 [ 0 13  0]
 [ 0 13  0]]
Classification Report:                precision    recall  f1-score   support

           0       0.00      0.00      0.00        19
           1       0.29      1.00      0.45        13
           2       0.00      0.00      0.00        13

    accuracy                           0.29        45
   macro avg       0.10      0.33      0.15        45
weighted avg       0.08      0.29      0.13        45



c:\Users\ghg\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ghg\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\ghg\miniconda3\envs\python_ml\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
