In [5]:
%pip install statsmodels

   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 393.8 kB/s eta 0:00:25
   ---------------------------------------- 0.1/9.9 MB 819.2 kB/s eta 0:00:12
   - -------------------------------------- 0.3/9.9 MB 1.6 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/9.9 MB 2.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.1/9.9 MB 4.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.1/9.9 MB 4.3 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.9 MB 3.5 MB/s eta 0:00:03
   ----- ---------------------------------- 1.3/9.9 MB 3.2 MB/s eta 0:00:03
   ----- ---------------------------------- 1.4/9.9 MB 3.2 MB/s eta 0:00:03
   ------ --------------------------------- 1.6/9.9 MB 3.2 MB/s eta 0:00:03
   ------ -------------------

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stats
import statsmodels.api as sm
# how to import sckikert learn library
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
%pip install statsmodels


Note: you may need to restart the kernel to use updated packages.


In [10]:
from sklearn import preprocessing
import numpy as np

# Define training data
X_train = np.array([[ 1., -1.,  2.],
                    [2.,  0.,  0.],
                    [0.,  1., -1.]])

# Fit the StandardScaler to the training data
scaler = preprocessing.StandardScaler().fit(X_train)

# Print the mean and scale of the scaler
print("Mean:", scaler.mean_)
print("Scale:", scaler.scale_)

# Transform the training data
X_scaled = scaler.transform(X_train)

# Print the scaled data
print("Scaled data:", X_scaled)

Mean: [1.         0.         0.33333333]
Scale: [0.81649658 0.81649658 1.24721913]
Scaled data: [[ 0.         -1.22474487  1.33630621]
 [ 1.22474487  0.         -0.26726124]
 [-1.22474487  1.22474487 -1.06904497]]


In [11]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [12]:
X_scaled.std(axis=0)

array([1., 1., 1.])

In [13]:
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

In [16]:
from sklearn.pipeline import Pipeline
X, y = make_classification(random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
pipe = make_pipeline(StandardScaler(), LogisticRegression())
pipe.fit(X_train, y_train)  # apply scaling on training data
Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression())])

pipe.score(X_test, y_test)  # apply scaling on testing data, without leaking training data.


0.96